defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: fengsweat
title: fengsweat
description: fengsweat博客
url: "http://fengsweat.github.io"

author:
  name: fengsweat
  email: join-tmallfe@list.alibaba-inc.com
  github: fengsweat
  bio: keep calm and carry on!

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:

markdown: kramdown
